/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.uis.elromasal.vista;

import co.edu.uis.elromasal.controlador.Controlador_Pantallas;
import co.edu.uis.elromasal.controlador.Controlador_Razas;
import co.edu.uis.elromasal.modelo.RazasAnimal;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class VistaRazas extends javax.swing.JFrame {

    /**
     * Creates new form VistaRazas
     */
    public VistaRazas() {
        initComponents();
        cargar_modelo_RazaAnimal();
    }

        public void limpiar_espacios(){
            txt_destinacion_raza.setText("");
            txt_id_raza.setText("");
            txt_nombre_raza.setText("");
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        lbl_razas = new javax.swing.JLabel();
        lbl_id_raza = new javax.swing.JLabel();
        lbl_Nombre_raza = new javax.swing.JLabel();
        lbl_Destinacion = new javax.swing.JLabel();
        btn_Registrar = new javax.swing.JButton();
        btn_Editar = new javax.swing.JButton();
        btn_listar = new javax.swing.JButton();
        btn_volver_al_menu = new javax.swing.JButton();
        btn_Eliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Raza = new javax.swing.JTable();
        txt_id_raza = new javax.swing.JTextField();
        txt_nombre_raza = new javax.swing.JTextField();
        txt_destinacion_raza = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_razas.setText("Razas");

        lbl_id_raza.setText("Id Raza");

        lbl_Nombre_raza.setText("Nombre");

        lbl_Destinacion.setText("Destinacion");

        btn_Registrar.setText("Registrar");
        btn_Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegistrarActionPerformed(evt);
            }
        });

        btn_Editar.setText("Editar");
        btn_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditarActionPerformed(evt);
            }
        });

        btn_listar.setText("Listar");
        btn_listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listarActionPerformed(evt);
            }
        });

        btn_volver_al_menu.setText("Volver al Menu");
        btn_volver_al_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volver_al_menuActionPerformed(evt);
            }
        });

        btn_Eliminar.setText("Eliminar");
        btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarActionPerformed(evt);
            }
        });

        tbl_Raza.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_Raza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_RazaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Raza);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_Registrar)
                                            .addComponent(btn_Editar))
                                        .addGap(28, 28, 28)
                                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_listar)
                                            .addComponent(btn_Eliminar)))
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(panelLayout.createSequentialGroup()
                                                .addComponent(lbl_Destinacion)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txt_destinacion_raza))
                                            .addGroup(panelLayout.createSequentialGroup()
                                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lbl_id_raza)
                                                    .addComponent(lbl_Nombre_raza))
                                                .addGap(33, 33, 33)
                                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txt_id_raza, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                                    .addComponent(txt_nombre_raza))))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                .addComponent(btn_volver_al_menu)
                                .addGap(42, 42, 42)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(lbl_razas)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_id_raza)
                    .addComponent(txt_id_raza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Nombre_raza)
                    .addComponent(txt_nombre_raza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Destinacion)
                    .addComponent(txt_destinacion_raza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Registrar)
                    .addComponent(btn_Eliminar))
                .addGap(46, 46, 46)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Editar)
                    .addComponent(btn_listar))
                .addGap(18, 18, 18)
                .addComponent(btn_volver_al_menu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_razas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void btn_RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegistrarActionPerformed
        int id_raza = Integer.parseInt(txt_id_raza.getText());
        String nombre = txt_nombre_raza.getText();
        String destinacion = txt_destinacion_raza.getText();
        RazasAnimal ra = new RazasAnimal(id_raza, nombre, destinacion);
        Controlador_Razas.guardar_Razas(ra);
        limpiar_espacios();
        
        Controlador_Razas.cargar_Razas(tbl_Raza, modelo_RazaAnimal);
        
        
    }//GEN-LAST:event_btn_RegistrarActionPerformed

    DefaultTableModel modelo_RazaAnimal = new DefaultTableModel();
    
    private void cargar_modelo_RazaAnimal () {
        modelo_RazaAnimal.addColumn("id");
        modelo_RazaAnimal.addColumn("nombre");
        modelo_RazaAnimal.addColumn("destinacion");
        
        tbl_Raza.setModel(modelo_RazaAnimal);
    }
            
    private void btn_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditarActionPerformed
        int id_raza = Integer.parseInt(txt_id_raza.getText());
        String nombre = txt_nombre_raza.getText();
        String destinacion = txt_destinacion_raza.getText();
        RazasAnimal ra = new RazasAnimal(id_raza, nombre, destinacion);
        Controlador_Razas.actualizar_Razas(ra);
        limpiar_espacios();
        
        Controlador_Razas.cargar_Razas(tbl_Raza, modelo_RazaAnimal);
        txt_id_raza.setEnabled(true);
    }//GEN-LAST:event_btn_EditarActionPerformed

    private void btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarActionPerformed
        int id = Integer.parseInt(JOptionPane.showInputDialog(null, "Digite el id que desea eliminar"));
        Controlador_Razas.eliminar_Razas(id, tbl_Raza, modelo_RazaAnimal);
        Controlador_Razas.cargar_Razas(tbl_Raza, modelo_RazaAnimal);
                
    }//GEN-LAST:event_btn_EliminarActionPerformed

    private void btn_listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listarActionPerformed
        Controlador_Razas.cargar_Razas(tbl_Raza, modelo_RazaAnimal);
    }//GEN-LAST:event_btn_listarActionPerformed

    private void tbl_RazaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_RazaMouseClicked
        cargar_editar_Razas();
    }//GEN-LAST:event_tbl_RazaMouseClicked

    private void btn_volver_al_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volver_al_menuActionPerformed
        Controlador_Pantallas.cerrar_pantalla_Razas();
        Controlador_Pantallas.abir_pantalla_menu();
    }//GEN-LAST:event_btn_volver_al_menuActionPerformed

    
    private void cargar_editar_Razas(){
        int seleccion_fila = tbl_Raza.getSelectedRow();
        if (seleccion_fila >= 0){
            txt_id_raza.setText((tbl_Raza.getValueAt(seleccion_fila, 0).toString()));
            txt_nombre_raza.setText((tbl_Raza.getValueAt(seleccion_fila, 1).toString()));
            txt_nombre_raza.setText((tbl_Raza.getValueAt(seleccion_fila, 2).toString()));
            
        }
        txt_id_raza.setEnabled(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRazas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRazas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRazas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRazas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRazas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Editar;
    private javax.swing.JButton btn_Eliminar;
    private javax.swing.JButton btn_Registrar;
    private javax.swing.JButton btn_listar;
    private javax.swing.JButton btn_volver_al_menu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Destinacion;
    private javax.swing.JLabel lbl_Nombre_raza;
    private javax.swing.JLabel lbl_id_raza;
    private javax.swing.JLabel lbl_razas;
    private javax.swing.JPanel panel;
    private javax.swing.JTable tbl_Raza;
    private javax.swing.JTextField txt_destinacion_raza;
    private javax.swing.JTextField txt_id_raza;
    private javax.swing.JTextField txt_nombre_raza;
    // End of variables declaration//GEN-END:variables
}
